name: Deploy UTA Cloud Automation Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Save EC2 SSH Key
      env:
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$KEY" > key.pem
        chmod 600 key.pem

    - name: Create Target Directory on EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "
          mkdir -p /home/$USER/uta-cloud-automation/scripts &&
          mkdir -p /home/$USER/uta-cloud-automation/scripts/lambda_package
        "

    - name: Copy Scripts to EC2 Server
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no -r ./scripts $USER@$HOST:/home/$USER/uta-cloud-automation/scripts

    - name: Copy Lambda Function to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p /home/$USER/uta-cloud-automation/scripts/lambda_package"
        scp -i key.pem -o StrictHostKeyChecking=no ./scripts/lambda_package/lambda_function.py $USER@$HOST:/home/$USER/uta-cloud-automation/scripts/lambda_package/lambda_function.py

    - name: Run Deployment Script on EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "cd /home/$USER/uta-cloud-automation/scripts && ./deploy.sh"

